### ISSUE TITLE
Installation instructions not working?

### ISSUE THREAD

**Issue by danwashusen** [tylertreat/Comcast#11]
OK, so I'm a total go n00b but the installation instructions don't seem to work...

```
$ brew install go
...
$ export GOPATH=~/.gocode
$ go get github.com/tylertreat/comcast
$ comcast --device=en0 --latency=250 --bandwidth=1000 --packet-loss=0.1
-bash: comcast: command not found
```

edit: brew installs ``go version go1.3.3 darwin/amd64``

**Comment by chrisgaraffa** [comment]
Add ~/.gocode/bin to your PATH:

    export PATH=~/gocode/bin:$PATH

**Comment by danwashusen** [comment]
@chrisgaraffa thanks :)
