### ISSUE TITLE
Comcast not working in OSX 10.10.1

### ISSUE THREAD

**Issue by dsilhavy** [tylertreat/Comcast#16]
Hi guys,
I just tried to setup Comcast on a MAC OS X 10.10.1 machine, resulting in the following message:
"I don't support your version of OSX".
Is there a way to get it working? Maybe by changing some codelines and building it by myself?

**Comment by th3m4ri0** [comment]
The file [throttler/throttler.go](../blob/master/throttler/throttler.go#L102) seems to be where it's at.
>func osxVersionSupported() bool {
	v, err := exec.Command("/bin/sh", "-c", checkOSXVersion).Output()
	if err != nil {
		return false
	}
	return !strings.HasPrefix(string(v), "10.10")
}

**Comment by Mike-Dunton** [comment]
Try changing line 107 in throttler.go 
to 
return !strings.HasPrefix(string(v), "10.10.1")

**Comment by tylertreat** [comment]
The utility Comcast uses as a backend for OSX (`ipfw`) was removed in 10.10 Yosemite. It should be theoretically possible to implement a backend which uses `pfctl` that would support Yosemite, but learning it looks a little more involved.

**Comment by Term1nal** [comment]
^ Basically this. Blame Apple. But I'm working toward supporting it eventually after I finish tc/iptables & ipfw overhaul. Will be hard without a Mac to test it on, but I have people that can do it for me :3

**Comment by dsilhavy** [comment]
Allright thank you for the fast response guys. I might try it on a Linux VM some time ;)

**Comment by tylertreat** [comment]
Yeah, I would say the "preferred" use case is on Linux for the time being, but it sounds like @Term1nal is working on some interesting stuff, so stay tuned.
