### ISSUE TITLE
Does comcat gave you money to named your code as their brand name ?

### ISSUE THREAD

**Issue by netroby** [tylertreat/Comcast#23]
Does comcat gave you money to named your code as their brand name ?

Do you afraid they may Sue you.

I like the name.

**Comment by Term1nal** [comment]
No, as stated a few times before by the original creator, the name was mostly an afterthought, but it is pretty appropriate when considering it satirically. Comcast surely wouldn't be very happy, but from the standpoint of being satirical, I think there's no real harm Comcast the company can do to this project other than make the creator change the name. If that is even possible from a legal standpoint.
