### ISSUE TITLE
MacOSX Support

### ISSUE THREAD

**Issue by Term1nal** [tylertreat/comcast#24]
I've come to the conclusion that PF does not include the features necessary to do the likes of arbitrary packet drop/reorder/corruption or delay. I can get working at the very least a bandwidth limit, and some packet drop may possible ensue from that by way of using a priority queue (PRIQ) setup where lower priority queues may lose packets if the data to the highest priority queue is saturated. But there's no way to finely control this behavior through means of configuration in similar fashion to TC and IPFW. So PF will only have very basic support for our purposes, thus leaving MacOSX 10.10.x poorly supported by the scope of this project.

**Comment by tchakabam** [comment]
Hi

Thanks for the clarification.

What would exactly be needed to be done to at least enable bandwidth limitation and packet loss probability?

How could one contribute to this? I have been working with TC before but I find it hard to find documentation on how to achieve even bandwidth control using PF. If you could provide some info here, I'd be happy to start a pull request.

**Comment by tylertreat** [comment]
Yeah, tbh I haven't spent the time looking through how PF works, and I probably won't be getting to it anytime soon. If anyone has any insight on this that would be awesome.

**Comment by Term1nal** [comment]
It's not possible with PF. It just doesn't have the feature. It's not a lacking of documentation (like how TC is). It's a lack of implementation.

**Comment by tylertreat** [comment]
Addressed in https://github.com/tylertreat/comcast/pull/35
