### ISSUE TITLE
Sources for Network Condition Profiles?

### ISSUE THREAD

**Issue by 1kastner** [tylertreat/comcast#63]
First of all thank you very much for sharing this project!
I wondered how you came up with the specific numbers in the section `Network Condition Profiles`?
Are they from some literature? Did you check it yourself?
Thank you very much in advance!

**Comment by tylertreat** [comment]
This data was added by a contributor who claims it's from literature/reliable sources, [see here](https://github.com/tylertreat/comcast/pull/7) for discussion. Happy to accept changes if you data with a source. :)
