### ISSUE TITLE
Legal fund

### ISSUE THREAD

**Issue by jgowdy** [tylertreat/Comcast#9]
Is there a place where we can donate to your legal fund when they hulk smash over the use of their mark?  Your tool seems too useful and functional to claim parody although obviously I'm no lawyer.

**Comment by rakeshjuyal** [comment]
I am not sure if I should mark it as issue. I think there is a typo in the name of this project. It's name should have been BSNL but it is misspelled as comcast.

**Comment by tylertreat** [comment]
There are a lot of other ISPs who I'm sure would be happy to have a
namesake.

**Comment by planetmcd** [comment]
Plot twist: @jgowdy is the person at Comcast whose job it is to reduce the cost of lawsuits.

**Comment by jgowdy** [comment]
lulz @planetmcd :+1:

**Comment by Fire-** [comment]
It's just an abbreviation of "Communications Castrator" ![MiniK](http://static-cdn.jtvnw.net/jtv_user_pictures/emoticon-2868-src-5a7a81bb829e1a4c-28x28.png "MiniK")

**Comment by Alienwaren** [comment]
@up You Sir are da real MVP

**Comment by derivator** [comment]
I believe this issue is related to #10. If that were implemented, I believe it would turn this project into political speech, to which the First Amendment would apply. (Disclaimer: I'm not a lawyer.)

**Comment by NewAlexandria** [comment]
Agreed that #10 reinforces [what I see as] all aspects this valuable piece of culture and technology.  This is a distinct tool from ChaosMonkey, and provides a valuable service that reflects the real challenges that are faced in delivering superior customer experiences.

**Comment by kgodwin** [comment]
Simulating the quality of the Comcast Internet Connection may also qualify as patent infringement as I'm sure Comcast has patented everything they could.

**Comment by dworzanski** [comment]
The name of this project is hysterical.

There shouldn't be any legal issues in the US given the nature of this product and the explicit protections on parody in trademark law. I'm not a lawyer, but been around the block with IP.
